### ISSUE TITLE
Add information about Hacktoberfest in README.md

### ISSUE THREAD

**Issue by bullyduck** [bullyduck/surprise-birthday-app-hacktoberfest#1]
Detailed information about Hacktoberfest is required with good and easy to understand English.

You can raise an [issue](https://github.com/bullyduck/surprise-birthday-app/issues) if you want to add in your native language.

**Comment by kumarutsav1123** [comment]
Please assign me

**Comment by SO-HYBE** [comment]
Assign me I can do that.

**Comment by bullyduck** [comment]
> Assign me I can do that.

Go ahead if you feel more details are needed to be added. Don't delete already accepted lines.
